//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADDCART.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderId { get; set; }
        public int productId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Orderr Orderr { get; set; }
        public virtual Orderr Orderr1 { get; set; }
    }
}
