//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICRUD.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentId { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public int DId { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
